DROP DATABASE IF EXISTS airbnbPost;
CREATE DATABASE airbnbPost;


USE airbnbPost;

CREATE TABLE photos (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  thumbnailURL VARCHAR(100),
  imageURL VARCHAR(100),
  description VARCHAR(1000),
  room VARCHAR(100),
);

CREATE TABLE listing (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100),
  description VARCHAR(1000),
  FOREIGN KEY(photos_id) REFERENCES photos(id)

);